In [202]:
import numpy as np

arr = np.random.randint(1, 50+1, size=(3,4))
print(f"Original Array:\n{arr}")

print(f"Mean = {np.mean(arr):.2f}")
print(f"Median = {np.median(arr):.2f}")
print(f"Standard Deviation = {np.std(arr):.2f}")

print(f"Sum of all elements = {np.sum(arr)}")
print(f"Sum of each row = {np.sum(arr, axis=1)}")

print(arr.reshape(2,6))

Original Array:
[[40 21  6 45]
 [13  3  2  5]
 [25 35 24 45]]
Mean = 22.00
Median = 22.50
Standard Deviation = 15.68
Sum of all elements = 264
Sum of each row = [112  23 129]
[[40 21  6 45 13  3]
 [ 2  5 25 35 24 45]]


In [23]:
import numpy as np

# Create two 3x3 matrices
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

print("\nMatrix Addition (A + B):\n", A + B)

print("\nMatrix Subtraction (A - B):\n", A - B)

print("\nElement-wise Multiplication (A * B):\n", A * B)

print("\nDot Product (A @ B):\n", A @ B)

print("\nTranspose of Matrix A:\n", A.T)

det_A = np.linalg.det(A)
print("\nDeterminant of Matrix A:", det_A)

if det_A != 0:
    inv_A = np.linalg.inv(A)
    print("\nInverse of Matrix A:\n", inv_A)
else:
    print("\nMatrix A is singular and does not have an inverse.")


Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix Addition (A + B):
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Subtraction (A - B):
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Element-wise Multiplication (A * B):
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Dot Product (A @ B):
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Transpose of Matrix A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

Determinant of Matrix A: 0.0

Matrix A is singular and does not have an inverse.
